### ISSUE TITLE
Mp4box declaration in Mp4info.js needs to be changed

### ISSUE THREAD

**Issue by segvic** [SVT/vivict#12]
Hi,
comparison of two mp4 files is throwing an exception - problem is the old declaration in the 
/src/util/Mp4Info.js line 46:
 const mp4boxfile = new MP4Box.MP4Box();

It needs to be changed to:
const mp4boxfile = new MP4Box.createFile();

Regards

**Comment by grusell** [comment]
Many thanks for reporting this, will fix!

Regards

**Comment by grusell** [comment]
@segvic can you tell me some details of how you got this error? I cannot reproduce it on the master branch. I have only been able to reproduce it by updating the mp4box version to 0.3.20 (master uses 0.3.15).

**Comment by segvic** [comment]
I experienced it on my local install, I am guessing latest version of Mp4box was installed as a dependency.
