### ISSUE TITLE
Will the PSNR or SSIM measurements involved in the future?

### ISSUE THREAD

**Issue by Cuberlain** [svt/vivict#16]
Hello!

Will the PSNR or SSIM measurements involve in your software in the future?

**Comment by bitbytebit-cr** [comment]
FYI this is a change I added in my branch / fork for some tests I am doing. It incorporates PHASH PHQM metric comparisons realtime across video frames (which mostly works, sometimes slows down / lags)...

https://github.com/svt/vivict/compare/master...bitbytebit-cr:master

**Comment by grusell** [comment]
Sorry for the late reply.

 @Cuberlain it would be nice, but I don't think I will find the time to add it. PRs are welcome of course :) .

@bitbytebit-cr Looks interesting! I will have a look and hopefully merge it into master.
