### ISSUE TITLE
Unable to load video in tool

### ISSUE THREAD

**Issue by mayoore** [svt/vivict#17]
[test.zip](https://github.com/svt/vivict/files/5703848/test.zip)
Unable to load the mp4 file attached. The file is zipped to comply with GitHub's restrictions.

**Comment by grusell** [comment]
Sorry for late reply.

As far as I can see the file is encoded with with Mpeg4 Visual codec. Likely the codec is not supported by your browser. I guess it would be nice if vivict would present an error message in this case :) .
