### ISSUE TITLE
Is it still in active development?

### ISSUE THREAD

**Issue by arthur-digby** [svt/vivict#19]
This is a great project. It has tons of useful features and it seems to have been thought out carefully. No other implementation of this type I have seen even comes close to this level of functionality.

I realize the online use must have been the main goal you had in mind with this app but I think it could serve at least some offline use cases. I'd like to use this locally to compare videos transcoded in different qualities but I'm a bit intimidated by the process. Do you intend to add more friendly install options, like appimage or deb? Also, are there any plans for an alternative file load workflow for local use? The current one is nicely optimized for online use cases.

Thank you for developing this project!

**Comment by grusell** [comment]
Glad you like the project! I guess you could say vivict is now in maintenance mode, bugs are fixed and requested features will be considered, but otherwise there is not much work at the moment.

You are right that online was the main intended usecase, but vivict does support viewing local files. There was some work on an electron version (ie standalone app that is in reality just the same app in a standalone browser), but since it didn't really add any functionality except the ability to run without internet access, it didn't seem to be worth the maintenance burden.

What kind of file load workflow would you have in mind for local use?

I should also mention that here is work underway on a vivict desktop app, with support for arbitrary codecs etc.

For offline use, you could also check out this app (I haven't tried it myself but looks nice): https://github.com/pixop/video-compare

**Comment by arthur-digby** [comment]
Thank you for taking the time to respond. It is good to know that expanding this project with improvements is still considered. An electron app sounds interesting and a standalone desktop app sounds even better. I would love to give it a try when it is going to be released.

By file load workflow I mean the interaction required to load the videos you want to compare. For a web only use case, copy-pasting a URL is really convenient. But if you want to specify a local source file, you have to first get the path and then type the filename after that. I mean it's not difficult, it's just not as friendly as using a browse dialog to choose your file and click on a "load" button. This is more like a nice to have feature that would improve the user experience. The actual feature set is more important and that one is solid. I am more concerned about being able to install this and use it properly. I am running Ubuntu as my OS but I am not a coder and I rely on conventional installers for running apps. That's why I am so glad to hear you are working on a desktop app.

Thanks for suggesting the alternative video compare tool. I don't think I've seen it, will take a look.

**Comment by chrizilla** [comment]
> @arthur-digby: « This is a great project. It has tons of useful features and it seems to have been thought out carefully. No other implementation of this type I have seen even comes close to this level of functionality.
> 
> I realize the online use must have been the main goal you had in mind with this app but I think it could serve at least some offline use cases. I'd like to use this locally to compare videos transcoded in different qualities but I'm a bit intimidated by the process. Do you intend to add more friendly install options, like appimage or deb? Also, are there any plans for an alternative file load workflow for local use? The current one is nicely optimized for online use cases.
> 
> Thank you for developing this project! »

I just wanted to write almost this exact same comment when I stumbled upon it. I second everything @arthur-digby says. Thanks for this awesome tool (if I can get it to work, that is ...). Was the movable slider your own idea? For years I have thought about a good way to compare video quality and this is hands down the very best solution! I hope I can get it to work. Thanks so much!

**Comment by grusell** [comment]
Glad you appreciate the projekt!

No the moving slider was not my idea, I got the idea it from a colleague
who probably got it from somewhere else. I think commercial product with
similar functionality has been around for a while.

Den tis 4 apr. 2023 01:45chrizilla ***@***.***> skrev:
